version: 2
jobs:
  test:
    docker:
      - image: previousnext/m8s:v0.4.1
    steps:
      - checkout
      - run:
          name: Test
          command: echo 'Run your tests here'
      - run:
          name: Environment
          command: |
            m8s build --git-revision=${CIRCLE_SHA1} \
                      --name=${CIRCLE_BRANCH} \
                      --domains=${CIRCLE_BRANCH}.nickschuch.com \
                      --basic-auth-user='nick' \
                      --basic-auth-pass='nick'

workflows:
  version: 2
  test:
    jobs:
      - test